global_frame: map
rolling_window: false
track_unknown_space: true
allow_unkown: true
static_map: true 
width: 15
height: 15

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}


